### ISSUE TITLE
Added missing return statements

### ISSUE THREAD

**Issue by AleksanderM** [petkovgogo/PP_fst_gsp#7]
Защо функцията main е int ако не връща нищо смислено?

**Comment by AleksanderM** [comment]
At e8d114d9598f9832a049cf2d22f1f351c04bb618

**Comment by petkovgogo** [comment]
Компилаторът дава грешка, ако се опитам да направя main функцията void

**Comment by AleksanderM** [comment]
Приемам забележката.
